-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_approval_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  analysis_type text NOT NULL,
  completeness_score integer,
  medical_necessity_score integer,
  approval_probability integer,
  missing_elements ARRAY,
  recommended_actions ARRAY,
  suggestions jsonb,
  analyzed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_approval_suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_approval_suggestions_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id)
);
CREATE TABLE public.alert_controls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alert_type character varying,
  patient character varying,
  message text,
  create_user character varying,
  is_global boolean DEFAULT false,
  patient_section boolean DEFAULT false,
  claim_section boolean DEFAULT false,
  payment_section boolean DEFAULT false,
  appointment_section boolean DEFAULT false,
  create_date_range character varying DEFAULT 'All'::character varying,
  create_date_start date,
  create_date_end date,
  effective_start_date_range character varying DEFAULT 'All'::character varying,
  effective_start_date_start date,
  effective_start_date_end date,
  effective_end_date_range character varying DEFAULT 'All'::character varying,
  effective_end_date_start date,
  effective_end_date_end date,
  include_deleted boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alert_controls_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alert_type character varying NOT NULL,
  patient character varying,
  message text NOT NULL,
  create_user character varying,
  is_global boolean DEFAULT false,
  patient_section boolean DEFAULT false,
  claim_section boolean DEFAULT false,
  payment_section boolean DEFAULT false,
  appointment_section boolean DEFAULT false,
  create_date_range character varying,
  create_date_start date,
  create_date_end date,
  effective_start_date_range character varying,
  effective_start_date_start date,
  effective_start_date_end date,
  effective_end_date_range character varying,
  effective_end_date_start date,
  effective_end_date_end date,
  include_deleted boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'active'::alert_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  patient_id_string character varying,
  provider_id uuid,
  facility_id uuid,
  appointment_type character varying,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 30,
  status USER-DEFINED DEFAULT 'scheduled'::appointment_status,
  location character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT appointments_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT appointments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.attorney_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  attorney_name text NOT NULL,
  attorney_firm text,
  attorney_contact text,
  referral_date date NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::attorney_referral_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT attorney_referrals_pkey PRIMARY KEY (id),
  CONSTRAINT attorney_referrals_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id),
  CONSTRAINT attorney_referrals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.authorization_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_email character varying,
  user_name character varying,
  authorization_request_id uuid NOT NULL,
  action character varying NOT NULL,
  action_category character varying NOT NULL,
  old_status character varying,
  new_status character varying,
  old_values jsonb,
  new_values jsonb,
  notes text,
  reason text,
  ip_address character varying,
  user_agent text,
  details jsonb,
  severity character varying DEFAULT 'medium'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT authorization_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT authorization_audit_logs_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id),
  CONSTRAINT authorization_audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.authorization_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  event_type text NOT NULL,
  payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT authorization_events_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_events_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id)
);
CREATE TABLE public.authorization_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  patient_name text NOT NULL,
  patient_dob date,
  patient_member_id text,
  payer_id uuid,
  payer_name_custom text,
  provider_name_custom text,
  provider_npi_custom text,
  service_type text,
  service_start_date date,
  service_end_date date,
  urgency_level text DEFAULT 'routine'::text,
  diagnosis_codes ARRAY,
  procedure_codes ARRAY,
  clinical_indication text,
  units_requested integer DEFAULT 1,
  status text DEFAULT 'draft'::text,
  pa_required boolean,
  submission_ref text,
  ack_status text,
  review_status text,
  auth_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  authorization_expiration_date date,
  expiration_alert_sent_tiers jsonb DEFAULT '[]'::jsonb,
  renewal_initiated boolean DEFAULT false,
  renewal_initiated_at timestamp with time zone,
  renewal_of_authorization_id uuid,
  renewal_status character varying,
  renewal_expected_response_date date,
  renewal_actual_response_date date,
  renewal_auth_number character varying,
  expired_at timestamp with time zone,
  expiration_handled boolean DEFAULT false,
  expiration_action character varying,
  expiration_impact_notes text,
  visits_authorized integer DEFAULT 0,
  visits_used integer DEFAULT 0,
  last_visit_date date,
  first_visit_date date,
  exhausted_at timestamp with time zone,
  company_id uuid,
  CONSTRAINT authorization_requests_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_requests_renewal_of_authorization_id_fkey FOREIGN KEY (renewal_of_authorization_id) REFERENCES public.authorization_requests(id),
  CONSTRAINT authorization_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT authorization_requests_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT authorization_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.authorization_task_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  is_internal boolean DEFAULT false,
  attachments jsonb,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT authorization_task_comments_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_task_comments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT authorization_task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.authorization_tasks(id),
  CONSTRAINT authorization_task_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.authorization_task_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  action character varying NOT NULL,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT authorization_task_history_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_task_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT authorization_task_history_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.authorization_tasks(id),
  CONSTRAINT authorization_task_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.authorization_task_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  task_type character varying NOT NULL,
  priority character varying DEFAULT 'medium'::character varying,
  estimated_duration_minutes integer,
  default_due_date_days integer,
  required_fields jsonb,
  workflow_steps jsonb,
  payer_specific boolean DEFAULT false,
  payer_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT authorization_task_templates_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_task_templates_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurance_payers(id)
);
CREATE TABLE public.authorization_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  task_type character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  assigned_to uuid,
  assigned_by uuid,
  assigned_at timestamp with time zone,
  priority character varying DEFAULT 'medium'::character varying,
  urgency_level character varying,
  status character varying DEFAULT 'pending'::character varying,
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  due_date timestamp with time zone,
  start_date timestamp with time zone,
  completed_at timestamp with time zone,
  estimated_duration_minutes integer,
  actual_duration_minutes integer,
  x12_submission_status character varying,
  x12_transaction_id character varying,
  x12_response_code character varying,
  x12_response_message text,
  x12_submitted_at timestamp with time zone,
  x12_response_received_at timestamp with time zone,
  depends_on_task_id uuid,
  blocks_task_id uuid,
  notes text,
  internal_notes text,
  attachments jsonb,
  reminder_sent_at timestamp with time zone,
  reminder_count integer DEFAULT 0,
  last_notified_at timestamp with time zone,
  escalated boolean DEFAULT false,
  escalated_at timestamp with time zone,
  escalated_to uuid,
  escalation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  company_id uuid,
  CONSTRAINT authorization_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_tasks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT authorization_tasks_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id),
  CONSTRAINT authorization_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT authorization_tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id),
  CONSTRAINT authorization_tasks_depends_on_task_id_fkey FOREIGN KEY (depends_on_task_id) REFERENCES public.authorization_tasks(id),
  CONSTRAINT authorization_tasks_blocks_task_id_fkey FOREIGN KEY (blocks_task_id) REFERENCES public.authorization_tasks(id),
  CONSTRAINT authorization_tasks_escalated_to_fkey FOREIGN KEY (escalated_to) REFERENCES auth.users(id),
  CONSTRAINT authorization_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.authorization_visit_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  appointment_id uuid,
  visit_date date NOT NULL,
  service_type character varying,
  cpt_codes ARRAY,
  provider_id uuid,
  visit_number integer NOT NULL,
  status character varying DEFAULT 'completed'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT authorization_visit_usage_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_visit_usage_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id),
  CONSTRAINT authorization_visit_usage_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT authorization_visit_usage_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT authorization_visit_usage_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.billing_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  frequency USER-DEFINED NOT NULL DEFAULT 'monthly'::billing_frequency,
  day_of_cycle integer NOT NULL DEFAULT 1,
  reminder_days ARRAY DEFAULT ARRAY[15, 30, 60],
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT billing_cycles_pkey PRIMARY KEY (id),
  CONSTRAINT billing_cycles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.billing_statements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  statement_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  amount_due numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  channel USER-DEFINED,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  viewed_at timestamp with time zone,
  paid_at timestamp with time zone,
  error_message text,
  pdf_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  company_id uuid,
  CONSTRAINT billing_statements_pkey PRIMARY KEY (id),
  CONSTRAINT billing_statements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT billing_statements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.charge_panel_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  charge_panel_id uuid NOT NULL,
  code character varying,
  pos character varying,
  tos character varying,
  modifier_options character varying DEFAULT 'Code Defaults'::character varying,
  modifier1 character varying,
  modifier2 character varying,
  modifier3 character varying,
  modifier4 character varying,
  price character varying DEFAULT 'Code Default'::character varying,
  units numeric DEFAULT 0.00,
  total character varying,
  other character varying,
  sequence_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT charge_panel_details_pkey PRIMARY KEY (id),
  CONSTRAINT charge_panel_details_charge_panel_id_fkey FOREIGN KEY (charge_panel_id) REFERENCES public.charge_panels(id)
);
CREATE TABLE public.charge_panels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  type character varying DEFAULT 'Professional'::character varying,
  description text,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT charge_panels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  status USER-DEFINED DEFAULT 'active'::chat_status,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  escalated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  company_id uuid,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT chat_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  message text NOT NULL,
  is_ai boolean DEFAULT true,
  sender_name text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.claim_additional_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL UNIQUE,
  form_data jsonb DEFAULT '{}'::jsonb,
  additional_info jsonb DEFAULT '{}'::jsonb,
  charge_options jsonb DEFAULT '{}'::jsonb,
  payment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_additional_data_pkey PRIMARY KEY (id),
  CONSTRAINT claim_additional_data_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size integer,
  file_url text,
  attachment_type text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT claim_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT claim_attachments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_denials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  denial_reason_code character varying,
  denial_reason text,
  denial_date date,
  resolved boolean DEFAULT false,
  resolution_date date,
  resolution_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT claim_denials_pkey PRIMARY KEY (id),
  CONSTRAINT claim_denials_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT claim_denials_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_diagnoses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  diagnosis_code_id uuid NOT NULL,
  diagnosis_type USER-DEFINED NOT NULL,
  diagnosis_pointer text,
  onset_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT claim_diagnoses_pkey PRIMARY KEY (id),
  CONSTRAINT claim_diagnoses_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_diagnoses_diagnosis_code_id_fkey FOREIGN KEY (diagnosis_code_id) REFERENCES public.diagnosis_codes(id),
  CONSTRAINT claim_diagnoses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.claim_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  note_type text NOT NULL,
  note_text text NOT NULL,
  is_internal boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT claim_notes_pkey PRIMARY KEY (id),
  CONSTRAINT claim_notes_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_physicians (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  physician_id uuid NOT NULL,
  physician_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_physicians_pkey PRIMARY KEY (id),
  CONSTRAINT claim_physicians_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_physicians_physician_id_fkey FOREIGN KEY (physician_id) REFERENCES public.providers(id)
);
CREATE TABLE public.claim_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  procedure_code_id uuid NOT NULL,
  procedure_date date NOT NULL,
  place_of_service_code USER-DEFINED,
  tooth_number text,
  tooth_surface ARRAY,
  tooth_system USER-DEFINED,
  oral_cavity_area USER-DEFINED,
  diagnosis_pointer text,
  quantity integer DEFAULT 1,
  unit_price numeric,
  total_charges numeric,
  is_emergency boolean DEFAULT false,
  modifier_codes ARRAY,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  service_date_from date,
  service_date_to date,
  type_of_service character varying,
  modifier_1 character varying,
  modifier_2 character varying,
  modifier_3 character varying,
  modifier_4 character varying,
  diagnosis_pointers character varying,
  status character varying,
  other character varying,
  company_id uuid,
  CONSTRAINT claim_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT claim_procedures_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_procedures_procedure_code_id_fkey FOREIGN KEY (procedure_code_id) REFERENCES public.procedure_codes(id),
  CONSTRAINT claim_procedures_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.claim_revenue_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  revenue_code_id uuid NOT NULL,
  service_date date,
  hcpcs_code text,
  units integer DEFAULT 1,
  total_charges numeric,
  non_covered_charges numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_revenue_codes_pkey PRIMARY KEY (id),
  CONSTRAINT claim_revenue_codes_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_revenue_codes_revenue_code_id_fkey FOREIGN KEY (revenue_code_id) REFERENCES public.revenue_codes(id)
);
CREATE TABLE public.claim_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  status_date timestamp with time zone DEFAULT now(),
  notes text,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT claim_status_history_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_number text NOT NULL UNIQUE,
  claim_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::claim_status,
  patient_id uuid NOT NULL,
  primary_insurance_id uuid,
  secondary_insurance_id uuid,
  tertiary_insurance_id uuid,
  billing_provider_id uuid,
  treating_provider_id uuid,
  facility_id uuid,
  service_start_date date,
  service_end_date date,
  admission_date date,
  discharge_date date,
  total_charges numeric DEFAULT 0,
  insurance_payment numeric DEFAULT 0,
  patient_responsibility numeric DEFAULT 0,
  adjustment_amount numeric DEFAULT 0,
  prior_authorization_number text,
  referral_number text,
  clinical_indication text,
  submission_date timestamp with time zone,
  processing_date timestamp with time zone,
  denial_reason text,
  appeal_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  additional_data jsonb DEFAULT '{}'::jsonb,
  reference_number character varying,
  frequency character varying DEFAULT '1 - Original Claim'::character varying,
  office_location character varying,
  supervising_provider_id uuid,
  ordering_provider_id uuid,
  referring_provider_id uuid,
  date_of_service date,
  CONSTRAINT claims_pkey PRIMARY KEY (id),
  CONSTRAINT claims_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT claims_primary_insurance_id_fkey FOREIGN KEY (primary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_secondary_insurance_id_fkey FOREIGN KEY (secondary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_tertiary_insurance_id_fkey FOREIGN KEY (tertiary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_billing_provider_id_fkey FOREIGN KEY (billing_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_treating_provider_id_fkey FOREIGN KEY (treating_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT claims_supervising_provider_id_fkey FOREIGN KEY (supervising_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_ordering_provider_id_fkey FOREIGN KEY (ordering_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_referring_provider_id_fkey FOREIGN KEY (referring_provider_id) REFERENCES public.providers(id)
);
CREATE TABLE public.code_validations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  code character varying NOT NULL,
  code_type USER-DEFINED NOT NULL,
  is_valid boolean,
  description text,
  errors jsonb DEFAULT '[]'::jsonb,
  warnings jsonb DEFAULT '[]'::jsonb,
  suggestions jsonb DEFAULT '[]'::jsonb,
  denial_risk_level character varying,
  denial_risk_score integer,
  denial_risk_factors jsonb DEFAULT '[]'::jsonb,
  denial_probability integer,
  recommendations jsonb DEFAULT '[]'::jsonb,
  validated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT code_validations_pkey PRIMARY KEY (id),
  CONSTRAINT code_validations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL,
  description text NOT NULL,
  type USER-DEFINED NOT NULL,
  price numeric,
  inactive boolean DEFAULT false,
  category character varying,
  modifier character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.collaboration_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type character varying NOT NULL,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT collaboration_events_pkey PRIMARY KEY (id),
  CONSTRAINT collaboration_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.collection_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  activity_type USER-DEFINED NOT NULL,
  contact_method USER-DEFINED,
  contact_person text,
  notes text,
  outcome text,
  follow_up_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  amount_discussed numeric,
  promise_to_pay_date date,
  performed_by text,
  company_id uuid,
  CONSTRAINT collection_activities_pkey PRIMARY KEY (id),
  CONSTRAINT collection_activities_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id),
  CONSTRAINT collection_activities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.collection_agencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  address text,
  address_line2 text,
  city character varying,
  state character varying,
  zip_code character varying,
  phone character varying,
  fax character varying,
  email character varying,
  agency_type character varying,
  status character varying DEFAULT 'active'::character varying,
  commission_rate numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  company_id uuid,
  CONSTRAINT collection_agencies_pkey PRIMARY KEY (id),
  CONSTRAINT collection_agencies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.collection_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  letter_type USER-DEFINED NOT NULL,
  sent_date date,
  delivery_method USER-DEFINED,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  CONSTRAINT collection_letters_pkey PRIMARY KEY (id),
  CONSTRAINT collection_letters_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id),
  CONSTRAINT collection_letters_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.collections_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  patient_id uuid,
  patient_name text NOT NULL,
  patient_email text,
  patient_phone text,
  original_balance numeric NOT NULL,
  current_balance numeric NOT NULL CHECK (current_balance >= 0::numeric),
  days_overdue integer NOT NULL DEFAULT 0,
  collection_stage USER-DEFINED NOT NULL DEFAULT 'early_collection'::collection_stage,
  collection_status USER-DEFINED NOT NULL DEFAULT 'active'::collection_status,
  assigned_to uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_contact_date timestamp with time zone,
  next_action_date timestamp with time zone,
  notes text,
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  company_id uuid,
  CONSTRAINT collections_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT collections_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT collections_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  domain character varying,
  logo_url text,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  country character varying DEFAULT 'USA'::character varying,
  phone character varying,
  email character varying,
  subscription_tier character varying DEFAULT 'basic'::character varying,
  subscription_status character varying DEFAULT 'active'::character varying,
  subscription_start_date date,
  subscription_end_date date,
  settings jsonb DEFAULT '{}'::jsonb,
  features jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_trial boolean DEFAULT false,
  trial_end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.company_form_report_access (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  form_report_id uuid NOT NULL,
  is_enabled boolean DEFAULT true,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_form_report_access_pkey PRIMARY KEY (id),
  CONSTRAINT company_form_report_access_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_form_report_access_form_report_id_fkey FOREIGN KEY (form_report_id) REFERENCES public.system_forms_reports(id)
);
CREATE TABLE public.company_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying DEFAULT 'user'::character varying,
  is_primary boolean DEFAULT false,
  permissions jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  invited_by uuid,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_users_pkey PRIMARY KEY (id),
  CONSTRAINT company_users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT company_users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  code character varying NOT NULL,
  price numeric DEFAULT 0.00,
  description text,
  type character varying DEFAULT 'Procedure'::character varying,
  exclude boolean DEFAULT false,
  sequence_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT contract_procedures_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type character varying DEFAULT 'FFS'::character varying,
  sequence_number character varying NOT NULL UNIQUE,
  allow_users_to_update_prices boolean DEFAULT true,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contracts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cpt_hcpcs_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL,
  type character varying DEFAULT 'CPT®/HCPCS'::character varying,
  dept character varying,
  description text NOT NULL,
  exclude_from_duplicate boolean DEFAULT false,
  all_inclusive boolean DEFAULT false,
  percentage_of_claim boolean DEFAULT false,
  default_price numeric DEFAULT 0.00,
  default_units numeric DEFAULT 1.00,
  default_charge_status character varying,
  rev_code character varying,
  place_of_service character varying,
  clia_number character varying,
  type_of_service character varying,
  narrative_notes text,
  additional_description text,
  global_modifier1 character varying,
  global_modifier2 character varying,
  global_modifier3 character varying,
  global_modifier4 character varying,
  icd1 character varying,
  icd2 character varying,
  icd3 character varying,
  icd4 character varying,
  global_surgery_period character varying DEFAULT 'None'::character varying,
  prior_auth_requirements character varying DEFAULT 'None'::character varying,
  drug_price numeric DEFAULT 0.00,
  drug_units numeric DEFAULT 1.00,
  drug_units_measure character varying DEFAULT 'Unit (UN)'::character varying,
  drug_code character varying,
  drug_code_format character varying,
  effective_date date,
  termination_date date,
  print_on_superbills boolean DEFAULT false,
  category character varying,
  superbill_description text,
  statement_description text,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cpt_hcpcs_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dental_missing_teeth (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  tooth_number integer NOT NULL,
  is_missing boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dental_missing_teeth_pkey PRIMARY KEY (id),
  CONSTRAINT dental_missing_teeth_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.dental_orthodontic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  is_orthodontic boolean DEFAULT false,
  appliance_placed_date date,
  months_remaining integer,
  is_replacement boolean DEFAULT false,
  prior_placement_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dental_orthodontic_pkey PRIMARY KEY (id),
  CONSTRAINT dental_orthodontic_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.diagnosis_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  code_type text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  effective_date date,
  termination_date date,
  cpt1 character varying,
  cpt2 character varying,
  cpt3 character varying,
  cpt4 character varying,
  cpt5 character varying,
  cpt6 character varying,
  print_on_superbill boolean DEFAULT false,
  superbill_description text,
  status character varying DEFAULT 'active'::character varying,
  CONSTRAINT diagnosis_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispute_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  dispute_reason text NOT NULL,
  dispute_amount numeric,
  status USER-DEFINED DEFAULT 'open'::dispute_status,
  resolution_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT dispute_claims_pkey PRIMARY KEY (id),
  CONSTRAINT dispute_claims_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id),
  CONSTRAINT dispute_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.edi_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  transaction_type USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::edi_transaction_status,
  patient_id character varying,
  payer_id uuid,
  claim_id uuid,
  amount numeric,
  error_message text,
  request_data jsonb,
  response_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT edi_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT edi_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT edi_transactions_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT edi_transactions_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.eligibility_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_email character varying,
  user_name character varying,
  eligibility_verification_id uuid NOT NULL,
  action character varying NOT NULL,
  action_category character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  notes text,
  reason text,
  ip_address character varying,
  user_agent text,
  details jsonb,
  severity character varying DEFAULT 'low'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT eligibility_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT eligibility_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT eligibility_audit_logs_eligibility_verification_id_fkey FOREIGN KEY (eligibility_verification_id) REFERENCES public.eligibility_verifications(id),
  CONSTRAINT eligibility_audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.eligibility_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  serial_no character varying UNIQUE,
  description text,
  provider_id uuid,
  provider_name character varying,
  npp_id uuid,
  npp_name character varying,
  facility_id uuid,
  appointment_location character varying,
  appointment_date date,
  date_of_service date,
  demographic character varying,
  type_of_visit character varying,
  service_type character varying,
  status USER-DEFINED DEFAULT 'pending'::eligibility_status,
  is_self_pay boolean DEFAULT false,
  patient_id character varying,
  patient_name character varying,
  patient_dob date,
  patient_gender character varying,
  patient_address text,
  patient_city character varying,
  patient_state character varying,
  patient_zip character varying,
  patient_phone character varying,
  subscriber_is_patient boolean DEFAULT true,
  subscriber_id character varying,
  subscriber_first_name character varying,
  subscriber_last_name character varying,
  subscriber_middle_initial character varying,
  subscriber_dob date,
  subscriber_gender character varying,
  subscriber_relationship character varying,
  subscriber_address text,
  subscriber_city character varying,
  subscriber_state character varying,
  subscriber_zip character varying,
  primary_insurance_id uuid,
  primary_insurance_name character varying,
  insurance_id character varying,
  group_number character varying,
  insurance_plan character varying,
  plan_type character varying,
  effective_date date,
  termination_date date,
  copay numeric,
  coinsurance numeric,
  deductible numeric,
  deductible_met numeric,
  out_of_pocket_remaining numeric,
  out_of_pocket_max numeric,
  in_network_status character varying,
  allowed_amount numeric,
  copay_before_deductible boolean DEFAULT true,
  deductible_status character varying,
  deductible_amount numeric,
  cpt_codes jsonb DEFAULT '[]'::jsonb,
  icd_codes jsonb DEFAULT '[]'::jsonb,
  secondary_insurance_name character varying,
  secondary_insurance_coverage character varying,
  secondary_insurance_id character varying,
  secondary_group_number character varying,
  secondary_relationship_code character varying,
  secondary_effective_date date,
  secondary_termination_date date,
  secondary_subscriber_first_name character varying,
  secondary_subscriber_last_name character varying,
  secondary_subscriber_dob date,
  secondary_subscriber_gender character varying,
  secondary_copay numeric,
  secondary_deductible numeric,
  secondary_deductible_met numeric,
  secondary_coinsurance numeric,
  cob_rule character varying,
  cob_indicator character varying,
  referral_required boolean DEFAULT false,
  referral_obtained_from character varying,
  referral_pcp_status character varying,
  referral_number character varying,
  pre_authorization_required boolean DEFAULT false,
  prior_auth_number character varying,
  prior_auth_status USER-DEFINED,
  prior_auth_request_date date,
  prior_auth_submission_date date,
  prior_auth_submission_method character varying,
  prior_auth_payer_confirmation_number character varying,
  prior_auth_expected_response_date date,
  prior_auth_response_date date,
  prior_auth_effective_date date,
  prior_auth_expiration_date date,
  prior_auth_denial_reason_code character varying,
  prior_auth_denial_reason text,
  prior_auth_approved_quantity integer,
  prior_auth_approved_frequency character varying,
  prior_auth_service_date date,
  prior_auth_appeal_submitted boolean DEFAULT false,
  prior_auth_appeal_date date,
  prior_auth_appeal_status character varying,
  prior_auth_appeal_decision_date date,
  previous_balance_credit numeric,
  patient_responsibility numeric,
  collection_amount numeric,
  estimated_cost numeric,
  billed_amount numeric,
  is_qmb boolean DEFAULT false,
  is_covered_service boolean DEFAULT true,
  primary_payment numeric,
  secondary_payment numeric,
  primary_coverage_percent numeric,
  secondary_coverage_percent numeric,
  remarks text,
  date_checked date DEFAULT CURRENT_DATE,
  verified_by character varying,
  verification_method character varying DEFAULT 'manual'::character varying,
  demographic_changes_made boolean DEFAULT false,
  qa boolean DEFAULT false,
  is_eligible boolean,
  verification_result jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT eligibility_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT eligibility_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT eligibility_verifications_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT eligibility_verifications_npp_id_fkey FOREIGN KEY (npp_id) REFERENCES public.providers(id),
  CONSTRAINT eligibility_verifications_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT eligibility_verifications_primary_insurance_id_fkey FOREIGN KEY (primary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT eligibility_verifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.facilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_name text NOT NULL,
  npi text UNIQUE,
  tax_id text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  phone text,
  fax text,
  email text,
  facility_type text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  taxonomy_specialty character varying,
  sequence_number character varying,
  reference_number character varying,
  clia_id character varying,
  location_provider_id character varying,
  site_id character varying,
  blue_cross_id character varying,
  blue_shield_id character varying,
  medicare_id character varying,
  medicaid_id character varying,
  locator_code character varying,
  place_of_service character varying,
  name character varying NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  company_id uuid,
  CONSTRAINT facilities_pkey PRIMARY KEY (id),
  CONSTRAINT facilities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.fee_schedule_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fee_schedule_id uuid NOT NULL,
  code character varying NOT NULL,
  price numeric DEFAULT 0.00,
  description text,
  type character varying DEFAULT 'Procedure'::character varying,
  sequence_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fee_schedule_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT fee_schedule_procedures_fee_schedule_id_fkey FOREIGN KEY (fee_schedule_id) REFERENCES public.fee_schedules(id)
);
CREATE TABLE public.fee_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  sequence_number character varying NOT NULL UNIQUE,
  effective_from date,
  effective_to date,
  price_creation_method character varying NOT NULL,
  creation_settings jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fee_schedules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.icd_procedure_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL,
  code_type character varying DEFAULT 'ICD-10'::character varying,
  description text NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT icd_procedure_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.institutional_claim_additional_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL UNIQUE,
  form_data jsonb DEFAULT '{}'::jsonb,
  additional_info jsonb DEFAULT '{}'::jsonb,
  charge_options jsonb DEFAULT '{}'::jsonb,
  payment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT institutional_claim_additional_data_pkey PRIMARY KEY (id),
  CONSTRAINT institutional_claim_additional_data_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.institutional_claims(id)
);
CREATE TABLE public.institutional_claim_diagnoses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  icd_code character varying NOT NULL,
  description text,
  is_primary boolean DEFAULT false,
  diagnosis_type character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT institutional_claim_diagnoses_pkey PRIMARY KEY (id),
  CONSTRAINT institutional_claim_diagnoses_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.institutional_claims(id)
);
CREATE TABLE public.institutional_claim_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  revenue_code character varying,
  hcpcs_code character varying,
  description text,
  quantity integer DEFAULT 1,
  unit_price numeric,
  total_price numeric,
  service_date_from date,
  service_date_to date,
  place_of_service_code character varying,
  diagnosis_pointers character varying,
  status character varying,
  other character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT institutional_claim_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT institutional_claim_procedures_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.institutional_claims(id)
);
CREATE TABLE public.institutional_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  claim_number character varying NOT NULL UNIQUE,
  form_type character varying DEFAULT 'UB04'::character varying,
  cms_form_version character varying,
  reference_number character varying,
  frequency character varying DEFAULT '1 - Original Claim'::character varying,
  office_location character varying,
  date_of_service date,
  patient_id uuid,
  patient_id_string character varying,
  provider_id uuid,
  facility_id uuid,
  appointment_id uuid,
  statement_covers_from date,
  statement_covers_to date,
  admission_date date,
  admission_type character varying,
  discharge_date date,
  discharge_hour character varying,
  place_of_service_code character varying,
  primary_insurance_id uuid,
  secondary_insurance_id uuid,
  tertiary_insurance_id uuid,
  insurance_type character varying DEFAULT 'EDI'::character varying,
  total_charges numeric DEFAULT 0,
  non_covered_charges numeric DEFAULT 0,
  patient_responsibility numeric DEFAULT 0,
  insurance_amount numeric DEFAULT 0,
  copay_amount numeric DEFAULT 0,
  deductible_amount numeric DEFAULT 0,
  prior_auth_number character varying,
  referral_number character varying,
  treatment_auth_code character varying,
  status USER-DEFINED DEFAULT 'draft'::claim_status,
  submission_method USER-DEFINED DEFAULT 'EDI'::submission_method,
  is_secondary_claim boolean DEFAULT false,
  submission_date date,
  additional_data jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT institutional_claims_pkey PRIMARY KEY (id),
  CONSTRAINT institutional_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT institutional_claims_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT institutional_claims_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id),
  CONSTRAINT institutional_claims_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT institutional_claims_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT institutional_claims_primary_insurance_id_fkey FOREIGN KEY (primary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT institutional_claims_secondary_insurance_id_fkey FOREIGN KEY (secondary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT institutional_claims_tertiary_insurance_id_fkey FOREIGN KEY (tertiary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT institutional_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.insurance_payers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  payer_id_code text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  payer_type text,
  contact_phone text,
  contact_email text,
  claims_address text,
  eligibility_phone text,
  prior_auth_required boolean DEFAULT false,
  plan_name character varying,
  network_status character varying,
  default_charge_status character varying,
  clearinghouse_processing_mode character varying,
  sequence_number character varying,
  reference_number character varying,
  group_number character varying,
  claim_office_number character varying,
  payer_id_medigap character varying,
  ocna character varying,
  use_alternate_practice_info boolean DEFAULT false,
  fax character varying,
  email character varying,
  website character varying,
  zip_code character varying,
  status character varying DEFAULT 'active'::character varying,
  address text,
  city character varying,
  state character varying,
  phone character varying,
  company_id uuid,
  CONSTRAINT insurance_payers_pkey PRIMARY KEY (id),
  CONSTRAINT insurance_payers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.inventory_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  procedure_code character varying,
  quantity integer DEFAULT 0,
  code_description text,
  billing_description text,
  use_alert boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.label_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  label_type USER-DEFINED NOT NULL,
  printer_type character varying,
  label_size character varying,
  font character varying,
  font_size character varying,
  bold boolean DEFAULT false,
  italics boolean DEFAULT false,
  column_spacing integer DEFAULT 15,
  columns jsonb DEFAULT '[]'::jsonb,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT label_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  recipient character varying NOT NULL,
  subject character varying,
  message text,
  type character varying NOT NULL,
  related_type character varying,
  related_id uuid,
  sent boolean DEFAULT false,
  sent_at timestamp with time zone,
  delivery_status character varying,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.patient_admissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  admission_date date NOT NULL,
  admission_hour time without time zone,
  admission_type USER-DEFINED,
  admission_source USER-DEFINED,
  discharge_date date,
  discharge_hour time without time zone,
  patient_status USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_admissions_pkey PRIMARY KEY (id),
  CONSTRAINT patient_admissions_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.patient_communication_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL UNIQUE,
  patient_name text NOT NULL,
  patient_email text,
  patient_phone text,
  preferred_channel USER-DEFINED NOT NULL DEFAULT 'email'::communication_channel,
  email_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  paper_enabled boolean DEFAULT false,
  portal_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  company_id uuid,
  CONSTRAINT patient_communication_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT patient_communication_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT patient_communication_preferences_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.patient_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  document_type USER-DEFINED NOT NULL,
  document_name character varying NOT NULL,
  description text,
  file_name character varying,
  file_size bigint,
  file_type character varying,
  file_url text,
  uploaded_by character varying,
  upload_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_documents_pkey PRIMARY KEY (id),
  CONSTRAINT patient_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patient_insurance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  insurance_company_id uuid NOT NULL,
  member_id text NOT NULL,
  group_number text,
  policy_holder_name text,
  policy_holder_relationship USER-DEFINED,
  policy_holder_dob date,
  policy_holder_ssn text,
  effective_date date,
  termination_date date,
  is_primary boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  company_id uuid,
  CONSTRAINT patient_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT patient_insurance_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_insurance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.patient_medical_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  allergies jsonb DEFAULT '[]'::jsonb,
  medications jsonb DEFAULT '[]'::jsonb,
  conditions jsonb DEFAULT '[]'::jsonb,
  surgeries jsonb DEFAULT '[]'::jsonb,
  family_history jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_medical_history_pkey PRIMARY KEY (id),
  CONSTRAINT patient_medical_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_medical_history_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patient_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  message_type USER-DEFINED NOT NULL,
  subject character varying NOT NULL,
  message text NOT NULL,
  priority USER-DEFINED DEFAULT 'normal'::message_priority,
  send_method character varying NOT NULL,
  scheduled_send boolean DEFAULT false,
  scheduled_time timestamp with time zone,
  sender character varying NOT NULL,
  status character varying DEFAULT 'sent'::character varying,
  sent_at timestamp with time zone,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_messages_pkey PRIMARY KEY (id),
  CONSTRAINT patient_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_messages_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patient_progress_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  note_type character varying,
  note_date date NOT NULL,
  note_time time without time zone,
  provider character varying,
  chief_complaint text,
  history_of_present_illness text,
  review_of_systems text,
  physical_examination text,
  assessment text,
  plan text,
  medications text,
  follow_up text,
  vital_signs text,
  allergies text,
  social_history text,
  family_history text,
  additional_notes text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_progress_notes_pkey PRIMARY KEY (id),
  CONSTRAINT patient_progress_notes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_progress_notes_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patient_treatment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  plan_date date NOT NULL,
  provider character varying,
  diagnosis text,
  treatment_goals text,
  treatment_plan text,
  medications text,
  procedures text,
  lifestyle_modifications text,
  follow_up_schedule text,
  expected_outcome text,
  risk_factors text,
  contraindications text,
  patient_education text,
  additional_notes text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_treatment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT patient_treatment_plans_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_treatment_plans_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patient_vital_signs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  blood_pressure_systolic integer,
  blood_pressure_diastolic integer,
  heart_rate integer,
  temperature numeric,
  respiratory_rate integer,
  oxygen_saturation numeric,
  weight numeric,
  height numeric,
  bmi numeric,
  pain_level integer,
  notes text,
  recorded_by character varying,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT patient_vital_signs_pkey PRIMARY KEY (id),
  CONSTRAINT patient_vital_signs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patient_vital_signs_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_initial text,
  suffix text,
  date_of_birth date NOT NULL,
  gender USER-DEFINED NOT NULL,
  ssn text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  phone_primary text,
  phone_secondary text,
  email text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  emergency_contact_relation character varying,
  marital_status character varying,
  race character varying,
  ethnicity character varying,
  language character varying,
  phone character varying,
  status character varying DEFAULT 'active'::character varying,
  risk_level character varying DEFAULT 'low'::character varying CHECK (risk_level::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  preferred_provider_id uuid,
  total_visits integer DEFAULT 0,
  outstanding_balance numeric DEFAULT 0,
  last_visit_date date,
  notes text,
  internal_notes text,
  company_id uuid,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT patients_preferred_provider_id_fkey FOREIGN KEY (preferred_provider_id) REFERENCES public.providers(id)
);
CREATE TABLE public.payer_agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_type USER-DEFINED DEFAULT 'individual'::provider_type,
  provider_name character varying NOT NULL,
  npi_type character varying DEFAULT 'practice'::character varying,
  practice_npi character varying,
  other_npi character varying,
  first_name character varying,
  last_name character varying,
  phone_number character varying,
  contact_email character varying,
  agreement_type character varying,
  status USER-DEFINED DEFAULT 'active'::payer_agreement_status,
  start_date date,
  end_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT payer_agreements_pkey PRIMARY KEY (id),
  CONSTRAINT payer_agreements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.payment_installments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_plan_id uuid NOT NULL,
  installment_number integer NOT NULL,
  due_date date NOT NULL,
  amount numeric NOT NULL,
  status text DEFAULT 'pending'::text,
  paid_at timestamp with time zone,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT payment_installments_pkey PRIMARY KEY (id),
  CONSTRAINT payment_installments_payment_plan_id_fkey FOREIGN KEY (payment_plan_id) REFERENCES public.payment_plans(id),
  CONSTRAINT payment_installments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.payment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  total_amount numeric NOT NULL,
  down_payment numeric DEFAULT 0,
  monthly_payment numeric NOT NULL,
  number_of_payments integer NOT NULL,
  start_date date NOT NULL,
  auto_pay boolean DEFAULT false,
  notes text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT payment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_plans_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.payment_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  statement_id uuid,
  patient_id text NOT NULL,
  reminder_type text NOT NULL,
  scheduled_for timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  channel USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT payment_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT payment_reminders_statement_id_fkey FOREIGN KEY (statement_id) REFERENCES public.billing_statements(id),
  CONSTRAINT payment_reminders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  claim_id uuid,
  payment_amount numeric NOT NULL,
  payment_date date NOT NULL,
  payment_method USER-DEFINED,
  check_number character varying,
  total_paid numeric,
  adjustments numeric,
  patient_responsibility numeric,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  payer_id uuid,
  remittance_advice jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT payments_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  resource character varying NOT NULL,
  action character varying NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.practices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  npi character varying NOT NULL UNIQUE,
  organization_type character varying,
  taxonomy_specialty character varying,
  reference_number character varying,
  tcn_prefix character varying,
  statement_tcn_prefix character varying,
  code character varying,
  address_line1 text,
  address_line2 text,
  city character varying,
  state character varying,
  zip_code character varying,
  time_zone character varying,
  phone character varying,
  fax character varying,
  email character varying,
  pay_to_same_as_primary boolean DEFAULT true,
  pay_to_address_line1 text,
  pay_to_address_line2 text,
  pay_to_city character varying,
  pay_to_state character varying,
  pay_to_zip_code character varying,
  pay_to_phone character varying,
  pay_to_fax character varying,
  pay_to_email character varying,
  status USER-DEFINED DEFAULT 'active'::practice_status,
  established_date date,
  provider_count integer DEFAULT 0,
  patient_count integer DEFAULT 0,
  monthly_revenue numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT practices_pkey PRIMARY KEY (id),
  CONSTRAINT practices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.procedure_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  code_type text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT procedure_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.professional_claim_additional_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL UNIQUE,
  form_data jsonb DEFAULT '{}'::jsonb,
  additional_info jsonb DEFAULT '{}'::jsonb,
  charge_options jsonb DEFAULT '{}'::jsonb,
  payment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_claim_additional_data_pkey PRIMARY KEY (id),
  CONSTRAINT professional_claim_additional_data_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.professional_claims(id)
);
CREATE TABLE public.professional_claim_diagnoses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  icd_code character varying NOT NULL,
  description text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_claim_diagnoses_pkey PRIMARY KEY (id),
  CONSTRAINT professional_claim_diagnoses_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.professional_claims(id)
);
CREATE TABLE public.professional_claim_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  cpt_code character varying NOT NULL,
  description text,
  quantity integer DEFAULT 1,
  unit_price numeric,
  total_price numeric,
  service_date_from date,
  service_date_to date,
  modifier_1 character varying,
  modifier_2 character varying,
  modifier_3 character varying,
  modifier_4 character varying,
  place_of_service_code character varying,
  type_of_service character varying,
  diagnosis_pointers character varying,
  status character varying,
  other character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_claim_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT professional_claim_procedures_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.professional_claims(id)
);
CREATE TABLE public.professional_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  claim_number character varying NOT NULL UNIQUE,
  form_type character varying DEFAULT 'HCFA'::character varying,
  cms_form_version character varying DEFAULT '02-12'::character varying,
  reference_number character varying,
  frequency character varying DEFAULT '1 - Original Claim'::character varying,
  office_location character varying,
  date_of_service date,
  patient_id uuid,
  patient_id_string character varying,
  provider_id uuid,
  billing_provider_id uuid,
  supervising_provider_id uuid,
  ordering_provider_id uuid,
  referring_provider_id uuid,
  appointment_id uuid,
  service_date_from date,
  service_date_to date,
  place_of_service_code character varying,
  facility_id uuid,
  primary_insurance_id uuid,
  secondary_insurance_id uuid,
  tertiary_insurance_id uuid,
  insurance_type character varying DEFAULT 'EDI'::character varying,
  total_charges numeric DEFAULT 0,
  patient_responsibility numeric DEFAULT 0,
  insurance_amount numeric DEFAULT 0,
  copay_amount numeric DEFAULT 0,
  deductible_amount numeric DEFAULT 0,
  prior_auth_number character varying,
  referral_number character varying,
  treatment_auth_code character varying,
  status USER-DEFINED DEFAULT 'draft'::claim_status,
  submission_method USER-DEFINED DEFAULT 'EDI'::submission_method,
  is_secondary_claim boolean DEFAULT false,
  submission_date date,
  additional_data jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT professional_claims_pkey PRIMARY KEY (id),
  CONSTRAINT professional_claims_billing_provider_id_fkey FOREIGN KEY (billing_provider_id) REFERENCES public.providers(id),
  CONSTRAINT professional_claims_supervising_provider_id_fkey FOREIGN KEY (supervising_provider_id) REFERENCES public.providers(id),
  CONSTRAINT professional_claims_ordering_provider_id_fkey FOREIGN KEY (ordering_provider_id) REFERENCES public.providers(id),
  CONSTRAINT professional_claims_referring_provider_id_fkey FOREIGN KEY (referring_provider_id) REFERENCES public.providers(id),
  CONSTRAINT professional_claims_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT professional_claims_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT professional_claims_primary_insurance_id_fkey FOREIGN KEY (primary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT professional_claims_secondary_insurance_id_fkey FOREIGN KEY (secondary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT professional_claims_tertiary_insurance_id_fkey FOREIGN KEY (tertiary_insurance_id) REFERENCES public.insurance_payers(id),
  CONSTRAINT professional_claims_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT professional_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT professional_claims_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT professional_claims_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_super_admin boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  npi text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_initial text,
  suffix text,
  title text,
  specialty_code text,
  license_number text,
  tax_id text,
  phone text,
  fax text,
  email text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  credentials character varying,
  provider_type USER-DEFINED DEFAULT 'individual'::provider_type,
  taxonomy_specialty character varying,
  sequence_number character varying,
  reference_number character varying,
  code character varying,
  practice_for_provider character varying,
  bill_claims_under character varying,
  check_eligibility_under character varying,
  use_id_number character varying,
  employer_identification_number character varying,
  bill_as character varying,
  bill_professional_claims boolean DEFAULT false,
  bill_institutional_claims boolean DEFAULT false,
  submitter_number character varying,
  tcn_prefix character varying,
  home_phone character varying,
  cell_phone character varying,
  fax_number character varying,
  pager_number character varying,
  specialty_license_number character varying,
  state_license_number character varying,
  anesthesia_license_number character varying,
  upin_number character varying,
  blue_cross_number character varying,
  tricare_champus_number character varying,
  rev_code character varying,
  default_facility character varying,
  status character varying DEFAULT 'active'::character varying,
  company_id uuid,
  CONSTRAINT providers_pkey PRIMARY KEY (id),
  CONSTRAINT providers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.referring_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  last_name character varying NOT NULL,
  first_name character varying NOT NULL,
  middle_initial character varying,
  credentials character varying,
  provider_type USER-DEFINED DEFAULT 'individual'::provider_type,
  referring_type character varying,
  do_not_send_on_claims boolean DEFAULT false,
  npi character varying UNIQUE,
  taxonomy_specialty character varying,
  sequence_number character varying,
  reference_number character varying,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  home_phone character varying,
  cell_phone character varying,
  phone character varying,
  fax character varying,
  pager character varying,
  email character varying,
  tax_id character varying,
  tax_id_type character varying,
  upin character varying,
  bcbs_id character varying,
  medicare_id character varying,
  medicaid_id character varying,
  champus_id character varying,
  specialty_license_number character varying,
  state_license_number character varying,
  anesthesia_license_number character varying,
  marketer character varying,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  company_id uuid,
  CONSTRAINT referring_providers_pkey PRIMARY KEY (id),
  CONSTRAINT referring_providers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.remittance_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL,
  type character varying DEFAULT 'Adj Reason'::character varying,
  information_level text DEFAULT 'INFO - This code represents general information only.'::text,
  include_on_denial_reports boolean DEFAULT false,
  include_on_adjustment_reports boolean DEFAULT false,
  report_description text,
  long_description text,
  use_memoline boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT remittance_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.revenue_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price numeric DEFAULT 0.00,
  exclude_from_duplicate boolean DEFAULT false,
  statement_description text,
  status character varying DEFAULT 'active'::character varying,
  CONSTRAINT revenue_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_system_role boolean DEFAULT false,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settlement_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  offer_amount numeric NOT NULL,
  discount_percentage numeric,
  payment_terms text,
  expiration_date date,
  status USER-DEFINED DEFAULT 'pending'::settlement_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT settlement_offers_pkey PRIMARY KEY (id),
  CONSTRAINT settlement_offers_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id),
  CONSTRAINT settlement_offers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.statement_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  format USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'enabled'::statement_template_status,
  description text,
  template_content text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT statement_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.super_admin_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  super_admin_id uuid,
  action character varying NOT NULL,
  target_type character varying,
  target_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT super_admin_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT super_admin_audit_log_super_admin_id_fkey FOREIGN KEY (super_admin_id) REFERENCES auth.users(id)
);
CREATE TABLE public.superbills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type USER-DEFINED DEFAULT 'form-based'::superbill_type,
  file_path text,
  file_name character varying,
  status character varying DEFAULT 'active'::character varying,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  company_id uuid,
  CONSTRAINT superbills_pkey PRIMARY KEY (id),
  CONSTRAINT superbills_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.system_forms_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type character varying NOT NULL,
  category character varying,
  description text,
  route_path character varying UNIQUE,
  icon character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_forms_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_form_report_access (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  form_report_id uuid NOT NULL,
  is_enabled boolean DEFAULT true,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_form_report_access_pkey PRIMARY KEY (id),
  CONSTRAINT user_form_report_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_form_report_access_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT user_form_report_access_form_report_id_fkey FOREIGN KEY (form_report_id) REFERENCES public.system_forms_reports(id)
);
CREATE TABLE public.user_notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  status_changes boolean DEFAULT true,
  due_date_reminders boolean DEFAULT true,
  overdue_alerts boolean DEFAULT true,
  approval_notifications boolean DEFAULT true,
  denial_notifications boolean DEFAULT true,
  task_assignment boolean DEFAULT true,
  reminder_days ARRAY DEFAULT ARRAY[1, 3, 7],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);