-- ============================================================================
-- SEED DATA FOR CPT_HCPCS_CODES TABLE
-- ============================================================================
-- This file contains sample CPT/HCPCS code data for testing and development
-- Run this in Supabase SQL Editor after creating the cpt_hcpcs_codes table
-- ============================================================================

-- Insert sample CPT/HCPCS codes
-- Note: Using consistent snake_case naming for all columns
INSERT INTO cpt_hcpcs_codes (
    code,
    type,
    dept,
    description,
    exclude_from_duplicate,
    all_inclusive,
    percentage_of_claim,
    default_price,
    default_units,
    default_charge_status,
    rev_code,
    place_of_service,
    clia_number,
    type_of_service,
    narrative_notes,
    additional_description,
    global_modifier1,
    global_modifier2,
    global_modifier3,
    global_modifier4,
    icd1,
    icd2,
    icd3,
    icd4,
    global_surgery_period,
    prior_auth_requirements,
    drug_price,
    drug_units,
    drug_units_measure,
    drug_code,
    drug_code_format,
    effective_date,
    termination_date,
    print_on_superbills,
    category,
    superbill_description,
    statement_description,
    status,
    is_active
) VALUES
-- Code 1: Ultrasound Head and Neck
(
    '76536',
    'CPT®/HCPCS',
    'Radiology',
    'US EXAM OF HEAD AND NECK',
    false,
    false,
    false,
    140.00,
    1.00,
    'active',
    NULL,
    '11',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Radiology',
    'US EXAM OF HEAD AND NECK',
    'Ultrasound examination of head and neck',
    'active',
    true
),

-- Code 2: Ultrasound Pelvic Complete
(
    '76856',
    'CPT®/HCPCS',
    'Radiology',
    'US EXAM PELVIC COMPLETE',
    false,
    false,
    false,
    150.00,
    1.00,
    'active',
    NULL,
    '11',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Radiology',
    'US EXAM PELVIC COMPLETE',
    'Complete pelvic ultrasound examination',
    'active',
    true
),

-- Code 3: CT Thorax Lung Cancer Screening
(
    '71271',
    'CPT®/HCPCS',
    'Radiology',
    'CT THORAX LUNG CANCER SCR C-',
    false,
    false,
    false,
    175.00,
    1.00,
    'active',
    NULL,
    '11',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Radiology',
    'CT THORAX LUNG CANCER SCR C-',
    'CT thorax lung cancer screening',
    'active',
    true
),

-- Code 4: Screening Mammography
(
    '77067',
    'CPT®/HCPCS',
    'Radiology',
    'SCR MAMMO BI INCL CAD',
    false,
    false,
    false,
    160.00,
    1.00,
    'active',
    NULL,
    '11',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Radiology',
    'SCR MAMMO BI INCL CAD',
    'Screening mammography bilateral including CAD',
    'active',
    true
),

-- Code 5: Office Visit Established Patient
(
    '99213',
    'CPT®/HCPCS',
    'Primary Care',
    'OFFICE/OUTPATIENT VISIT EST',
    false,
    false,
    false,
    150.00,
    1.00,
    'active',
    NULL,
    '11',
    NULL,
    NULL,
    NULL,
    NULL,
    '25',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Evaluation and Management',
    'OFFICE/OUTPATIENT VISIT EST',
    'Office visit established patient',
    'active',
    true
),

-- Code 6: HCPCS Code - Wheelchair
(
    'E1399',
    'CPT®/HCPCS',
    'DME',
    'DURABLE MEDICAL EQUIPMENT',
    false,
    false,
    false,
    500.00,
    1.00,
    'active',
    NULL,
    '12',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'Certain Payers Only',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    'DME',
    'DURABLE MEDICAL EQUIPMENT',
    'Durable medical equipment',
    'active',
    true
),

-- Code 7: Surgery Code with Global Period
(
    '27447',
    'CPT®/HCPCS',
    'Surgery',
    'ARTHROPLASTY KNEE CONDYLE',
    false,
    true,
    false,
    5000.00,
    1.00,
    'active',
    NULL,
    '24',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '90 days',
    'All Payers',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Surgery',
    'ARTHROPLASTY KNEE CONDYLE',
    'Arthroplasty knee condyle',
    'active',
    true
),

-- Code 8: Inactive Code (for testing)
(
    '99999',
    'CPT®/HCPCS',
    NULL,
    'INACTIVE TEST CODE',
    false,
    false,
    false,
    0.00,
    1.00,
    'inactive',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'None',
    'None',
    0.00,
    1.00,
    'Unit (UN)',
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    NULL,
    'INACTIVE TEST CODE',
    NULL,
    'inactive',
    false
);

-- Verify the insert
SELECT 
    COUNT(*) as total_codes,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_codes,
    COUNT(CASE WHEN status = 'inactive' THEN 1 END) as inactive_codes
FROM cpt_hcpcs_codes;

-- Display all inserted codes
SELECT 
    code,
    type,
    description,
    default_price,
    category,
    status,
    created_at
FROM cpt_hcpcs_codes
ORDER BY created_at DESC;

