-- ============================================================================
-- SEED DATA FOR INSURANCE PAYERS TABLE
-- ============================================================================
-- This file contains sample payer data for testing and development
-- Run this in Supabase SQL Editor after creating the insurance_payers table
-- ============================================================================

-- Insert sample insurance payers
-- Note: Using consistent snake_case naming for all columns
INSERT INTO insurance_payers (
    name,
    plan_name,
    network_status,
    payer_type,
    default_charge_status,
    clearinghouse_processing_mode,
    sequence_number,
    reference_number,
    payer_id_code,
    address,
    city,
    state,
    zip_code,
    phone,
    fax,
    email,
    website,
    group_number,
    claim_office_number,
    payer_id_medigap,
    ocna,
    use_alternate_practice_info,
    status,
    is_active
) VALUES
-- Payer 1: Blue Cross Blue Shield
(
    'Blue Cross Blue Shield',
    'BCBS Standard Plan',
    'In Network',
    'Commercial',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will print and mail the claims',
    'NEW',
    'REF001',
    'BCBS001',
    '123 Insurance Boulevard',
    'Chicago',
    'IL',
    '60601',
    '(312) 555-0100',
    '(312) 555-0101',
    'info@bcbs.com',
    'www.bcbs.com',
    'GRP001',
    'CO001',
    'PID001',
    'OCNA001',
    false,
    'active',
    true
),

-- Payer 2: Medicare
(
    'Medicare',
    'Medicare Part B',
    'In Network',
    'Medicare',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF002',
    'MC002',
    '7500 Security Boulevard',
    'Baltimore',
    'MD',
    '21244',
    '(800) 633-4227',
    NULL,
    'info@medicare.gov',
    'www.medicare.gov',
    NULL,
    'CO002',
    NULL,
    NULL,
    false,
    'active',
    true
),

-- Payer 3: Medicaid
(
    'Medicaid',
    'Medicaid Standard',
    'In Network',
    'Medicaid',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF003',
    'MD003',
    '200 Independence Avenue SW',
    'Washington',
    'DC',
    '20201',
    '(202) 619-0257',
    NULL,
    'info@medicaid.gov',
    'www.medicaid.gov',
    NULL,
    'CO003',
    NULL,
    NULL,
    false,
    'active',
    true
),

-- Payer 4: Aetna
(
    'Aetna',
    'Aetna Health Plan',
    'In Network',
    'Commercial',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF004',
    'AET004',
    '151 Farmington Avenue',
    'Hartford',
    'CT',
    '06156',
    '(800) 872-3862',
    '(860) 273-0123',
    'info@aetna.com',
    'www.aetna.com',
    'GRP004',
    'CO004',
    NULL,
    'OCNA004',
    false,
    'active',
    true
),

-- Payer 5: UnitedHealthcare
(
    'UnitedHealthcare',
    'UHC Choice Plus',
    'In Network',
    'Commercial',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF005',
    'UHC005',
    '9900 Bren Road East',
    'Minnetonka',
    'MN',
    '55343',
    '(866) 270-5588',
    '(952) 936-1300',
    'info@uhc.com',
    'www.uhc.com',
    'GRP005',
    'CO005',
    NULL,
    'OCNA005',
    false,
    'active',
    true
),

-- Payer 6: Cigna
(
    'Cigna',
    'Cigna Open Access Plus',
    'In Network',
    'Commercial',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF006',
    'CIG006',
    '900 Cottage Grove Road',
    'Bloomfield',
    'CT',
    '06002',
    '(800) 997-1654',
    '(860) 226-6000',
    'info@cigna.com',
    'www.cigna.com',
    'GRP006',
    'CO006',
    NULL,
    'OCNA006',
    false,
    'active',
    true
),

-- Payer 7: Humana
(
    'Humana',
    'Humana Gold Plus',
    'In Network',
    'Commercial',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF007',
    'HUM007',
    '500 West Main Street',
    'Louisville',
    'KY',
    '40202',
    '(800) 457-4708',
    '(502) 580-1000',
    'info@humana.com',
    'www.humana.com',
    'GRP007',
    'CO007',
    NULL,
    'OCNA007',
    false,
    'active',
    true
),

-- Payer 8: Tricare
(
    'Tricare',
    'Tricare Prime',
    'In Network',
    'Tricare',
    'Send to Payer via Clearinghouse',
    'The clearinghouse will send claims electronically',
    'NEW',
    'REF008',
    'TRC008',
    '7700 Arlington Boulevard',
    'Falls Church',
    'VA',
    '22042',
    '(800) 538-9552',
    NULL,
    'info@tricare.mil',
    'www.tricare.mil',
    NULL,
    'CO008',
    NULL,
    NULL,
    false,
    'active',
    true
),

-- Payer 9: Workers Compensation
(
    'Workers Compensation Insurance',
    'WC Standard Plan',
    'Both',
    'Workers Compensation',
    'Hold for Review',
    'Manual processing required',
    'NEW',
    'REF009',
    'WC009',
    '100 State Street',
    'Albany',
    'NY',
    '12207',
    '(518) 474-2121',
    NULL,
    'info@wcb.ny.gov',
    'www.wcb.ny.gov',
    NULL,
    'CO009',
    NULL,
    NULL,
    true,
    'active',
    true
),

-- Payer 10: Inactive Payer (for testing)
(
    'Inactive Insurance Company',
    'Inactive Plan',
    'Unknown',
    'Other',
    'Do Not Send',
    'Manual processing required',
    'NEW',
    'REF010',
    'INACT010',
    '999 Inactive Street',
    'Detroit',
    'MI',
    '48201',
    '(313) 555-0000',
    NULL,
    'inactive@example.com',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    false,
    'inactive',
    false
);

-- Verify the insert
SELECT 
    COUNT(*) as total_payers,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_payers,
    COUNT(CASE WHEN status = 'inactive' THEN 1 END) as inactive_payers
FROM insurance_payers;

-- Display all inserted payers
SELECT 
    name,
    plan_name,
    payer_type,
    network_status,
    city,
    state,
    status,
    created_at
FROM insurance_payers
ORDER BY created_at DESC;

