-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_approval_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  analysis_type text NOT NULL,
  completeness_score integer,
  medical_necessity_score integer,
  approval_probability integer,
  missing_elements ARRAY,
  recommended_actions ARRAY,
  suggestions jsonb,
  analyzed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_approval_suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_approval_suggestions_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id)
);
CREATE TABLE public.attorney_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  attorney_name text NOT NULL,
  attorney_firm text,
  attorney_contact text,
  referral_date date NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::attorney_referral_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attorney_referrals_pkey PRIMARY KEY (id),
  CONSTRAINT attorney_referrals_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id)
);
CREATE TABLE public.authorization_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_request_id uuid NOT NULL,
  event_type text NOT NULL,
  payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT authorization_events_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_events_authorization_request_id_fkey FOREIGN KEY (authorization_request_id) REFERENCES public.authorization_requests(id)
);
CREATE TABLE public.authorization_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  patient_name text NOT NULL,
  patient_dob date,
  patient_member_id text,
  payer_id uuid,
  payer_name_custom text,
  provider_name_custom text,
  provider_npi_custom text,
  service_type text,
  service_start_date date,
  service_end_date date,
  urgency_level text DEFAULT 'routine'::text,
  diagnosis_codes ARRAY,
  procedure_codes ARRAY,
  clinical_indication text,
  units_requested integer DEFAULT 1,
  status text DEFAULT 'draft'::text,
  pa_required boolean,
  submission_ref text,
  ack_status text,
  review_status text,
  auth_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  CONSTRAINT authorization_requests_pkey PRIMARY KEY (id),
  CONSTRAINT authorization_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT authorization_requests_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurance_payers(id)
);
CREATE TABLE public.billing_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  frequency USER-DEFINED NOT NULL DEFAULT 'monthly'::billing_frequency,
  day_of_cycle integer NOT NULL DEFAULT 1,
  reminder_days ARRAY DEFAULT ARRAY[15, 30, 60],
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_cycles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_statements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  statement_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  amount_due numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  channel USER-DEFINED,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  viewed_at timestamp with time zone,
  paid_at timestamp with time zone,
  error_message text,
  pdf_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  CONSTRAINT billing_statements_pkey PRIMARY KEY (id),
  CONSTRAINT billing_statements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  status USER-DEFINED DEFAULT 'active'::chat_status,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  escalated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  message text NOT NULL,
  is_ai boolean DEFAULT true,
  sender_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.claim_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size integer,
  file_url text,
  attachment_type text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT claim_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT claim_attachments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_diagnoses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  diagnosis_code_id uuid NOT NULL,
  diagnosis_type USER-DEFINED NOT NULL,
  diagnosis_pointer text,
  onset_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_diagnoses_pkey PRIMARY KEY (id),
  CONSTRAINT claim_diagnoses_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_diagnoses_diagnosis_code_id_fkey FOREIGN KEY (diagnosis_code_id) REFERENCES public.diagnosis_codes(id)
);
CREATE TABLE public.claim_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  note_type text NOT NULL,
  note_text text NOT NULL,
  is_internal boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT claim_notes_pkey PRIMARY KEY (id),
  CONSTRAINT claim_notes_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claim_physicians (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  physician_id uuid NOT NULL,
  physician_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_physicians_pkey PRIMARY KEY (id),
  CONSTRAINT claim_physicians_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_physicians_physician_id_fkey FOREIGN KEY (physician_id) REFERENCES public.providers(id)
);
CREATE TABLE public.claim_procedures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  procedure_code_id uuid NOT NULL,
  procedure_date date NOT NULL,
  place_of_service USER-DEFINED,
  tooth_number text,
  tooth_surface ARRAY,
  tooth_system USER-DEFINED,
  oral_cavity_area USER-DEFINED,
  diagnosis_pointer text,
  quantity integer DEFAULT 1,
  unit_price numeric,
  total_charges numeric,
  is_emergency boolean DEFAULT false,
  modifier_codes ARRAY,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_procedures_pkey PRIMARY KEY (id),
  CONSTRAINT claim_procedures_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_procedures_procedure_code_id_fkey FOREIGN KEY (procedure_code_id) REFERENCES public.procedure_codes(id)
);
CREATE TABLE public.claim_revenue_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  revenue_code_id uuid NOT NULL,
  service_date date,
  hcpcs_code text,
  units integer DEFAULT 1,
  total_charges numeric,
  non_covered_charges numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_revenue_codes_pkey PRIMARY KEY (id),
  CONSTRAINT claim_revenue_codes_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_revenue_codes_revenue_code_id_fkey FOREIGN KEY (revenue_code_id) REFERENCES public.revenue_codes(id)
);
CREATE TABLE public.claim_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  status_date timestamp with time zone DEFAULT now(),
  notes text,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT claim_status_history_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_number text NOT NULL UNIQUE,
  claim_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::claim_status,
  patient_id uuid NOT NULL,
  primary_insurance_id uuid,
  secondary_insurance_id uuid,
  tertiary_insurance_id uuid,
  billing_provider_id uuid,
  treating_provider_id uuid,
  facility_id uuid,
  service_start_date date,
  service_end_date date,
  admission_date date,
  discharge_date date,
  total_charges numeric DEFAULT 0,
  insurance_payment numeric DEFAULT 0,
  patient_responsibility numeric DEFAULT 0,
  adjustment_amount numeric DEFAULT 0,
  prior_authorization_number text,
  referral_number text,
  clinical_indication text,
  submission_date timestamp with time zone,
  processing_date timestamp with time zone,
  denial_reason text,
  appeal_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT claims_pkey PRIMARY KEY (id),
  CONSTRAINT claims_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT claims_primary_insurance_id_fkey FOREIGN KEY (primary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_secondary_insurance_id_fkey FOREIGN KEY (secondary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_tertiary_insurance_id_fkey FOREIGN KEY (tertiary_insurance_id) REFERENCES public.patient_insurance(id),
  CONSTRAINT claims_billing_provider_id_fkey FOREIGN KEY (billing_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_treating_provider_id_fkey FOREIGN KEY (treating_provider_id) REFERENCES public.providers(id),
  CONSTRAINT claims_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.collection_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  activity_type USER-DEFINED NOT NULL,
  contact_method USER-DEFINED,
  contact_person text,
  notes text,
  outcome text,
  follow_up_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  amount_discussed numeric,
  promise_to_pay_date date,
  performed_by text,
  CONSTRAINT collection_activities_pkey PRIMARY KEY (id),
  CONSTRAINT collection_activities_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id)
);
CREATE TABLE public.collection_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  letter_type USER-DEFINED NOT NULL,
  sent_date date,
  delivery_method USER-DEFINED,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collection_letters_pkey PRIMARY KEY (id),
  CONSTRAINT collection_letters_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id)
);
CREATE TABLE public.collections_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  patient_id uuid,
  patient_name text NOT NULL,
  patient_email text,
  patient_phone text,
  original_balance numeric NOT NULL,
  current_balance numeric NOT NULL CHECK (current_balance >= 0::numeric),
  days_overdue integer NOT NULL DEFAULT 0,
  collection_stage USER-DEFINED NOT NULL DEFAULT 'early_collection'::collection_stage,
  collection_status USER-DEFINED NOT NULL DEFAULT 'active'::collection_status,
  assigned_to uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_contact_date timestamp with time zone,
  next_action_date timestamp with time zone,
  notes text,
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  CONSTRAINT collections_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT collections_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.dental_missing_teeth (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  tooth_number integer NOT NULL,
  is_missing boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dental_missing_teeth_pkey PRIMARY KEY (id),
  CONSTRAINT dental_missing_teeth_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.dental_orthodontic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  is_orthodontic boolean DEFAULT false,
  appliance_placed_date date,
  months_remaining integer,
  is_replacement boolean DEFAULT false,
  prior_placement_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dental_orthodontic_pkey PRIMARY KEY (id),
  CONSTRAINT dental_orthodontic_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.diagnosis_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  code_type text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diagnosis_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispute_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  dispute_reason text NOT NULL,
  dispute_amount numeric,
  status USER-DEFINED DEFAULT 'open'::dispute_status,
  resolution_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispute_claims_pkey PRIMARY KEY (id),
  CONSTRAINT dispute_claims_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id)
);
CREATE TABLE public.facilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_name text NOT NULL,
  npi text UNIQUE,
  tax_id text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  phone text,
  fax text,
  email text,
  facility_type text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT facilities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.insurance_payers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  payer_id_code text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  payer_type text,
  contact_phone text,
  contact_email text,
  claims_address text,
  eligibility_phone text,
  prior_auth_required boolean DEFAULT false,
  CONSTRAINT insurance_payers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patient_admissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  admission_date date NOT NULL,
  admission_hour time without time zone,
  admission_type USER-DEFINED,
  admission_source USER-DEFINED,
  discharge_date date,
  discharge_hour time without time zone,
  patient_status USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_admissions_pkey PRIMARY KEY (id),
  CONSTRAINT patient_admissions_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.patient_communication_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL UNIQUE,
  patient_name text NOT NULL,
  patient_email text,
  patient_phone text,
  preferred_channel USER-DEFINED NOT NULL DEFAULT 'email'::communication_channel,
  email_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  paper_enabled boolean DEFAULT false,
  portal_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_last_name text,
  patient_first_name text,
  patient_middle_initial text,
  patient_suffix text,
  CONSTRAINT patient_communication_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT patient_communication_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.patient_insurance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  insurance_company_id uuid NOT NULL,
  member_id text NOT NULL,
  group_number text,
  policy_holder_name text,
  policy_holder_relationship USER-DEFINED,
  policy_holder_dob date,
  policy_holder_ssn text,
  effective_date date,
  termination_date date,
  is_primary boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT patient_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT patient_insurance_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_initial text,
  suffix text,
  date_of_birth date NOT NULL,
  gender USER-DEFINED NOT NULL,
  ssn text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  phone_primary text,
  phone_secondary text,
  email text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT patients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_installments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_plan_id uuid NOT NULL,
  installment_number integer NOT NULL,
  due_date date NOT NULL,
  amount numeric NOT NULL,
  status text DEFAULT 'pending'::text,
  paid_at timestamp with time zone,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_installments_pkey PRIMARY KEY (id),
  CONSTRAINT payment_installments_payment_plan_id_fkey FOREIGN KEY (payment_plan_id) REFERENCES public.payment_plans(id)
);
CREATE TABLE public.payment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  patient_id text NOT NULL,
  patient_name text NOT NULL,
  total_amount numeric NOT NULL,
  down_payment numeric DEFAULT 0,
  monthly_payment numeric NOT NULL,
  number_of_payments integer NOT NULL,
  start_date date NOT NULL,
  auto_pay boolean DEFAULT false,
  notes text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  statement_id uuid,
  patient_id text NOT NULL,
  reminder_type text NOT NULL,
  scheduled_for timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  channel USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::statement_status,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT payment_reminders_statement_id_fkey FOREIGN KEY (statement_id) REFERENCES public.billing_statements(id)
);
CREATE TABLE public.procedure_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  code_type text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT procedure_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  npi text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_initial text,
  suffix text,
  title text,
  specialty_code text,
  license_number text,
  tax_id text,
  phone text,
  fax text,
  email text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.revenue_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  description text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settlement_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collection_account_id uuid NOT NULL,
  offer_amount numeric NOT NULL,
  discount_percentage numeric,
  payment_terms text,
  expiration_date date,
  status USER-DEFINED DEFAULT 'pending'::settlement_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settlement_offers_pkey PRIMARY KEY (id),
  CONSTRAINT settlement_offers_collection_account_id_fkey FOREIGN KEY (collection_account_id) REFERENCES public.collections_accounts(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);